fix: pin toolchain at 1.54.0
1.55.0 broke the build:

```
error: unused borrow that must be used
   --> anki/rslib/src/sync/http_client.rs:330:1
    |
330 | #[pin_project]
    | ^^^^^^^^^^^^^^
    |
note: the lint level is defined here
   --> anki/rslib/src/lib.rs:4:9
    |
4   | #![deny(unused_must_use)]
    |         ^^^^^^^^^^^^^^^
    = note: this error originates in the derive macro
    `::pin_project::__private::__PinProjectInternalDerive`
     (in Nightly builds, run with -Z macro-backtrace for more info)

```